apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ubacqruu
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ubacqruu:1e21769fb1abbfa0becfea08e4dcdf564c26d120@sha256:df6ed523cffcb96f02dd256ae23cb3af293a34c1aad6183940f6efe90ed92de9
          name: container-image
