apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ubacqruu
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ubacqruu:5434960012387f9c3088a5182ec62e45183274df@sha256:e9cc926c7c6bcb9cd62f6af469fe99dd9ae7c44b859e16ce1659fec7b7276e00
          name: container-image
